@0xdbb9ad1f14bf0b36;  # unique file ID, generated by `capnp id`

struct Person {
  name @0 :Text;
  birthdate @3 :Date;

  email @1 :Text;
  phones @2 :List(PhoneNumber);

  struct PhoneNumber {
    number @0 :Text;
    type @1 :Type;

    enum Type {
      mobile @0;
      home @1;
      work @2;
    }
  }
}

struct Date {
  year @0 :Int16;
  month @1 :UInt8;
  day @2 :UInt8;
}

struct TestGeneric(T) {
  typed @0 :List(T);
  any @1 :AnyList;
}

#interface TestPassThrough(T) {
#  getTypeList @0 () -> (result :List(T));
#  setTypeList @1 (result :List(T)) -> ();
#  getAnyList @2 () -> (result :AnyList);
#  setAnyList @3 (result :AnyList) -> ();
#}