// @generated by the capnpc-rust plugin to the Cap'n Proto schema compiler.
// DO NOT EDIT.
// source: rpc-twoparty.capnp
// capnp binary version: 1.0.1
// capnpc crate version: 0.25.3

#[repr(u16)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Side {
    Server = 0,
    Client = 1,
}

impl ::capnp::introspect::Introspect for Side {
    fn introspect() -> ::capnp::introspect::Type {
        ::capnp::introspect::TypeVariant::Enum(::capnp::introspect::RawEnumSchema {
            encoded_node: &side::ENCODED_NODE,
            annotation_types: side::get_annotation_types,
        })
        .into()
    }
}
impl ::core::convert::From<Side> for ::capnp::dynamic_value::Reader<'_> {
    fn from(e: Side) -> Self {
        ::capnp::dynamic_value::Enum::new(
            e.into(),
            ::capnp::introspect::RawEnumSchema {
                encoded_node: &side::ENCODED_NODE,
                annotation_types: side::get_annotation_types,
            }
            .into(),
        )
        .into()
    }
}
impl ::core::convert::TryFrom<u16> for Side {
    type Error = ::capnp::NotInSchema;
    fn try_from(
        value: u16,
    ) -> ::core::result::Result<Self, <Side as ::core::convert::TryFrom<u16>>::Error> {
        match value {
            0 => ::core::result::Result::Ok(Self::Server),
            1 => ::core::result::Result::Ok(Self::Client),
            n => ::core::result::Result::Err(::capnp::NotInSchema(n)),
        }
    }
}
impl From<Side> for u16 {
    #[inline]
    fn from(x: Side) -> u16 {
        x as u16
    }
}
impl ::capnp::traits::HasTypeId for Side {
    const TYPE_ID: u64 = 0x9fd6_9ebc_87b9_719cu64;
}
mod side {
    pub(crate) static ENCODED_NODE: [::capnp::Word; 25] = ::capnp::word_array([
        *b"\x00\x00\x00\x00\x05\x00\x06\x00",
        *b"\x9cq\xb9\x87\xbc\x9e\xd6\x9f",
        *b"\x13\x00\x00\x00\x02\x00\x00\x00",
        *b"\xa1\xf2\xda\x5c\x88\xc7\x84\xa1",
        *b"\x00\x00\x00\x00\x00\x00\x00\x00",
        *b"\x00\x00\x00\x00\x00\x00\x00\x00",
        *b"\x15\x00\x00\x00\xc2\x00\x00\x00",
        *b"\x1d\x00\x00\x00\x07\x00\x00\x00",
        *b"\x00\x00\x00\x00\x00\x00\x00\x00",
        *b"\x19\x00\x00\x007\x00\x00\x00",
        *b"\x00\x00\x00\x00\x00\x00\x00\x00",
        *b"\x00\x00\x00\x00\x00\x00\x00\x00",
        *b"rpc-twop",
        *b"arty.cap",
        *b"np:Side\x00",
        *b"\x00\x00\x00\x00\x01\x00\x01\x00",
        *b"\x08\x00\x00\x00\x01\x00\x02\x00",
        *b"\x00\x00\x00\x00\x00\x00\x00\x00",
        *b"\x11\x00\x00\x00:\x00\x00\x00",
        *b"\x00\x00\x00\x00\x00\x00\x00\x00",
        *b"\x01\x00\x00\x00\x00\x00\x00\x00",
        *b"\x09\x00\x00\x00:\x00\x00\x00",
        *b"\x00\x00\x00\x00\x00\x00\x00\x00",
        *b"server\x00\x00",
        *b"client\x00\x00",
    ]);
    pub(crate) fn get_annotation_types(
        child_index: Option<u16>,
        index: u32,
    ) -> ::capnp::introspect::Type {
        ::capnp::introspect::panic_invalid_annotation_indices(child_index, index)
    }
}

pub mod vat_id {
    #[derive(Copy, Clone)]
    pub struct Owned(());
    impl ::capnp::introspect::Introspect for Owned {
        fn introspect() -> ::capnp::introspect::Type {
            ::capnp::introspect::TypeVariant::Struct(::capnp::introspect::RawBrandedStructSchema {
                generic: &_private::RAW_SCHEMA,
                field_types: _private::get_field_types,
                annotation_types: _private::get_annotation_types,
            })
            .into()
        }
    }
    impl ::capnp::traits::Owned for Owned {
        type Reader<'a> = Reader<'a>;
        type Builder<'a> = Builder<'a>;
    }
    impl ::capnp::traits::OwnedStruct for Owned {
        type Reader<'a> = Reader<'a>;
        type Builder<'a> = Builder<'a>;
    }
    impl ::capnp::traits::Pipelined for Owned {
        type Pipeline = Pipeline;
    }

    pub struct Reader<'a> {
        reader: ::capnp::private::layout::StructReader<'a>,
    }
    impl ::core::marker::Copy for Reader<'_> {}
    impl ::core::clone::Clone for Reader<'_> {
        fn clone(&self) -> Self {
            *self
        }
    }

    impl ::capnp::traits::HasTypeId for Reader<'_> {
        const TYPE_ID: u64 = _private::TYPE_ID;
    }
    impl<'a> ::core::convert::From<::capnp::private::layout::StructReader<'a>> for Reader<'a> {
        fn from(reader: ::capnp::private::layout::StructReader<'a>) -> Self {
            Self { reader }
        }
    }

    impl<'a> ::core::convert::From<Reader<'a>> for ::capnp::dynamic_value::Reader<'a> {
        fn from(reader: Reader<'a>) -> Self {
            Self::Struct(::capnp::dynamic_struct::Reader::new(
                reader.reader,
                ::capnp::schema::StructSchema::new(::capnp::introspect::RawBrandedStructSchema {
                    generic: &_private::RAW_SCHEMA,
                    field_types: _private::get_field_types,
                    annotation_types: _private::get_annotation_types,
                }),
            ))
        }
    }

    impl ::core::fmt::Debug for Reader<'_> {
        fn fmt(
            &self,
            f: &mut ::core::fmt::Formatter<'_>,
        ) -> ::core::result::Result<(), ::core::fmt::Error> {
            core::fmt::Debug::fmt(
                &::core::convert::Into::<::capnp::dynamic_value::Reader<'_>>::into(*self),
                f,
            )
        }
    }

    impl<'a> ::capnp::traits::FromPointerReader<'a> for Reader<'a> {
        fn get_from_pointer(
            reader: &::capnp::private::layout::PointerReader<'a>,
            default: ::core::option::Option<&'a [::capnp::Word]>,
        ) -> ::capnp::Result<Self> {
            ::core::result::Result::Ok(reader.get_struct(default)?.into())
        }
    }

    impl<'a> ::capnp::traits::IntoInternalStructReader<'a> for Reader<'a> {
        fn into_internal_struct_reader(self) -> ::capnp::private::layout::StructReader<'a> {
            self.reader
        }
    }

    impl<'a> ::capnp::traits::Imbue<'a> for Reader<'a> {
        fn imbue(&mut self, cap_table: &'a ::capnp::private::layout::CapTable) {
            self.reader
                .imbue(::capnp::private::layout::CapTableReader::Plain(cap_table))
        }
    }

    impl Reader<'_> {
        pub fn reborrow(&self) -> Reader<'_> {
            Self { ..*self }
        }

        pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
            self.reader.total_size()
        }
        #[inline]
        pub fn get_side(
            self,
        ) -> ::core::result::Result<crate::rpc_twoparty_capnp::Side, ::capnp::NotInSchema> {
            ::core::convert::TryFrom::try_from(self.reader.get_data_field::<u16>(0))
        }
    }

    pub struct Builder<'a> {
        builder: ::capnp::private::layout::StructBuilder<'a>,
    }
    impl ::capnp::traits::HasStructSize for Builder<'_> {
        const STRUCT_SIZE: ::capnp::private::layout::StructSize =
            ::capnp::private::layout::StructSize {
                data: 1,
                pointers: 0,
            };
    }
    impl ::capnp::traits::HasTypeId for Builder<'_> {
        const TYPE_ID: u64 = _private::TYPE_ID;
    }
    impl<'a> ::core::convert::From<::capnp::private::layout::StructBuilder<'a>> for Builder<'a> {
        fn from(builder: ::capnp::private::layout::StructBuilder<'a>) -> Self {
            Self { builder }
        }
    }

    impl<'a> ::core::convert::From<Builder<'a>> for ::capnp::dynamic_value::Builder<'a> {
        fn from(builder: Builder<'a>) -> Self {
            Self::Struct(::capnp::dynamic_struct::Builder::new(
                builder.builder,
                ::capnp::schema::StructSchema::new(::capnp::introspect::RawBrandedStructSchema {
                    generic: &_private::RAW_SCHEMA,
                    field_types: _private::get_field_types,
                    annotation_types: _private::get_annotation_types,
                }),
            ))
        }
    }

    impl<'a> ::capnp::traits::ImbueMut<'a> for Builder<'a> {
        fn imbue_mut(&mut self, cap_table: &'a mut ::capnp::private::layout::CapTable) {
            self.builder
                .imbue(::capnp::private::layout::CapTableBuilder::Plain(cap_table))
        }
    }

    impl<'a> ::capnp::traits::FromPointerBuilder<'a> for Builder<'a> {
        fn init_pointer(builder: ::capnp::private::layout::PointerBuilder<'a>, _size: u32) -> Self {
            builder
                .init_struct(<Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE)
                .into()
        }
        fn get_from_pointer(
            builder: ::capnp::private::layout::PointerBuilder<'a>,
            default: ::core::option::Option<&'a [::capnp::Word]>,
        ) -> ::capnp::Result<Self> {
            ::core::result::Result::Ok(
                builder
                    .get_struct(
                        <Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE,
                        default,
                    )?
                    .into(),
            )
        }
    }

    impl ::capnp::traits::SetterInput<Owned> for Reader<'_> {
        fn set_pointer_builder(
            mut pointer: ::capnp::private::layout::PointerBuilder<'_>,
            value: Self,
            canonicalize: bool,
        ) -> ::capnp::Result<()> {
            pointer.set_struct(&value.reader, canonicalize)
        }
    }

    impl<'a> Builder<'a> {
        pub fn into_reader(self) -> Reader<'a> {
            self.builder.into_reader().into()
        }
        pub fn reborrow(&mut self) -> Builder<'_> {
            Builder {
                builder: self.builder.reborrow(),
            }
        }
        pub fn reborrow_as_reader(&self) -> Reader<'_> {
            self.builder.as_reader().into()
        }

        pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
            self.builder.as_reader().total_size()
        }
        #[inline]
        pub fn get_side(
            self,
        ) -> ::core::result::Result<crate::rpc_twoparty_capnp::Side, ::capnp::NotInSchema> {
            ::core::convert::TryFrom::try_from(self.builder.get_data_field::<u16>(0))
        }
        #[inline]
        pub fn set_side(&mut self, value: crate::rpc_twoparty_capnp::Side) {
            self.builder.set_data_field::<u16>(0, value as u16);
        }
    }

    pub struct Pipeline {
        _typeless: ::capnp::any_pointer::Pipeline,
    }
    impl ::capnp::capability::FromTypelessPipeline for Pipeline {
        fn new(typeless: ::capnp::any_pointer::Pipeline) -> Self {
            Self {
                _typeless: typeless,
            }
        }
    }
    impl Pipeline {}
    mod _private {
        pub(crate) static ENCODED_NODE: [::capnp::Word; 33] = ::capnp::word_array([
            *b"\x00\x00\x00\x00\x05\x00\x06\x00",
            *b"\x8e:s\xee\x9f\x90\x0b\xd2",
            *b"\x13\x00\x00\x00\x01\x00\x01\x00",
            *b"\xa1\xf2\xda\x5c\x88\xc7\x84\xa1",
            *b"\x00\x00\x07\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x15\x00\x00\x00\xca\x00\x00\x00",
            *b"!\x00\x00\x00\x07\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x1d\x00\x00\x00?\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"rpc-twop",
            *b"arty.cap",
            *b"np:VatId",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x01\x00\x01\x00",
            *b"\x04\x00\x00\x00\x03\x00\x04\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x01\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x0d\x00\x00\x00*\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x08\x00\x00\x00\x03\x00\x01\x00",
            *b"\x14\x00\x00\x00\x02\x00\x01\x00",
            *b"side\x00\x00\x00\x00",
            *b"\x0f\x00\x00\x00\x00\x00\x00\x00",
            *b"\x9cq\xb9\x87\xbc\x9e\xd6\x9f",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x0f\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
        ]);
        pub(crate) fn get_field_types(index: u16) -> ::capnp::introspect::Type {
            match index {
                0 => {
                    <crate::rpc_twoparty_capnp::Side as ::capnp::introspect::Introspect>::introspect(
                    )
                }
                _ => ::capnp::introspect::panic_invalid_field_index(index),
            }
        }
        pub(crate) fn get_annotation_types(
            child_index: Option<u16>,
            index: u32,
        ) -> ::capnp::introspect::Type {
            ::capnp::introspect::panic_invalid_annotation_indices(child_index, index)
        }
        pub(crate) static ARENA: ::capnp::private::arena::GeneratedCodeArena =
            ::capnp::private::arena::GeneratedCodeArena::new(&ENCODED_NODE);
        pub(crate) static RAW_SCHEMA: ::capnp::introspect::RawStructSchema =
            ::capnp::introspect::RawStructSchema::new(
                &ARENA,
                NONUNION_MEMBERS,
                MEMBERS_BY_DISCRIMINANT,
                MEMBERS_BY_NAME,
            );
        pub(crate) static NONUNION_MEMBERS: &[u16] = &[0];
        pub(crate) static MEMBERS_BY_DISCRIMINANT: &[u16] = &[];
        pub(crate) static MEMBERS_BY_NAME: &[u16] = &[0];
        pub(crate) const TYPE_ID: u64 = 0xd20b_909f_ee73_3a8e;
    }
}

pub mod provision_id {
    #[derive(Copy, Clone)]
    pub struct Owned(());
    impl ::capnp::introspect::Introspect for Owned {
        fn introspect() -> ::capnp::introspect::Type {
            ::capnp::introspect::TypeVariant::Struct(::capnp::introspect::RawBrandedStructSchema {
                generic: &_private::RAW_SCHEMA,
                field_types: _private::get_field_types,
                annotation_types: _private::get_annotation_types,
            })
            .into()
        }
    }
    impl ::capnp::traits::Owned for Owned {
        type Reader<'a> = Reader<'a>;
        type Builder<'a> = Builder<'a>;
    }
    impl ::capnp::traits::OwnedStruct for Owned {
        type Reader<'a> = Reader<'a>;
        type Builder<'a> = Builder<'a>;
    }
    impl ::capnp::traits::Pipelined for Owned {
        type Pipeline = Pipeline;
    }

    pub struct Reader<'a> {
        reader: ::capnp::private::layout::StructReader<'a>,
    }
    impl ::core::marker::Copy for Reader<'_> {}
    impl ::core::clone::Clone for Reader<'_> {
        fn clone(&self) -> Self {
            *self
        }
    }

    impl ::capnp::traits::HasTypeId for Reader<'_> {
        const TYPE_ID: u64 = _private::TYPE_ID;
    }
    impl<'a> ::core::convert::From<::capnp::private::layout::StructReader<'a>> for Reader<'a> {
        fn from(reader: ::capnp::private::layout::StructReader<'a>) -> Self {
            Self { reader }
        }
    }

    impl<'a> ::core::convert::From<Reader<'a>> for ::capnp::dynamic_value::Reader<'a> {
        fn from(reader: Reader<'a>) -> Self {
            Self::Struct(::capnp::dynamic_struct::Reader::new(
                reader.reader,
                ::capnp::schema::StructSchema::new(::capnp::introspect::RawBrandedStructSchema {
                    generic: &_private::RAW_SCHEMA,
                    field_types: _private::get_field_types,
                    annotation_types: _private::get_annotation_types,
                }),
            ))
        }
    }

    impl ::core::fmt::Debug for Reader<'_> {
        fn fmt(
            &self,
            f: &mut ::core::fmt::Formatter<'_>,
        ) -> ::core::result::Result<(), ::core::fmt::Error> {
            core::fmt::Debug::fmt(
                &::core::convert::Into::<::capnp::dynamic_value::Reader<'_>>::into(*self),
                f,
            )
        }
    }

    impl<'a> ::capnp::traits::FromPointerReader<'a> for Reader<'a> {
        fn get_from_pointer(
            reader: &::capnp::private::layout::PointerReader<'a>,
            default: ::core::option::Option<&'a [::capnp::Word]>,
        ) -> ::capnp::Result<Self> {
            ::core::result::Result::Ok(reader.get_struct(default)?.into())
        }
    }

    impl<'a> ::capnp::traits::IntoInternalStructReader<'a> for Reader<'a> {
        fn into_internal_struct_reader(self) -> ::capnp::private::layout::StructReader<'a> {
            self.reader
        }
    }

    impl<'a> ::capnp::traits::Imbue<'a> for Reader<'a> {
        fn imbue(&mut self, cap_table: &'a ::capnp::private::layout::CapTable) {
            self.reader
                .imbue(::capnp::private::layout::CapTableReader::Plain(cap_table))
        }
    }

    impl Reader<'_> {
        pub fn reborrow(&self) -> Reader<'_> {
            Self { ..*self }
        }

        pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
            self.reader.total_size()
        }
        #[inline]
        pub fn get_join_id(self) -> u32 {
            self.reader.get_data_field::<u32>(0)
        }
    }

    pub struct Builder<'a> {
        builder: ::capnp::private::layout::StructBuilder<'a>,
    }
    impl ::capnp::traits::HasStructSize for Builder<'_> {
        const STRUCT_SIZE: ::capnp::private::layout::StructSize =
            ::capnp::private::layout::StructSize {
                data: 1,
                pointers: 0,
            };
    }
    impl ::capnp::traits::HasTypeId for Builder<'_> {
        const TYPE_ID: u64 = _private::TYPE_ID;
    }
    impl<'a> ::core::convert::From<::capnp::private::layout::StructBuilder<'a>> for Builder<'a> {
        fn from(builder: ::capnp::private::layout::StructBuilder<'a>) -> Self {
            Self { builder }
        }
    }

    impl<'a> ::core::convert::From<Builder<'a>> for ::capnp::dynamic_value::Builder<'a> {
        fn from(builder: Builder<'a>) -> Self {
            Self::Struct(::capnp::dynamic_struct::Builder::new(
                builder.builder,
                ::capnp::schema::StructSchema::new(::capnp::introspect::RawBrandedStructSchema {
                    generic: &_private::RAW_SCHEMA,
                    field_types: _private::get_field_types,
                    annotation_types: _private::get_annotation_types,
                }),
            ))
        }
    }

    impl<'a> ::capnp::traits::ImbueMut<'a> for Builder<'a> {
        fn imbue_mut(&mut self, cap_table: &'a mut ::capnp::private::layout::CapTable) {
            self.builder
                .imbue(::capnp::private::layout::CapTableBuilder::Plain(cap_table))
        }
    }

    impl<'a> ::capnp::traits::FromPointerBuilder<'a> for Builder<'a> {
        fn init_pointer(builder: ::capnp::private::layout::PointerBuilder<'a>, _size: u32) -> Self {
            builder
                .init_struct(<Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE)
                .into()
        }
        fn get_from_pointer(
            builder: ::capnp::private::layout::PointerBuilder<'a>,
            default: ::core::option::Option<&'a [::capnp::Word]>,
        ) -> ::capnp::Result<Self> {
            ::core::result::Result::Ok(
                builder
                    .get_struct(
                        <Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE,
                        default,
                    )?
                    .into(),
            )
        }
    }

    impl ::capnp::traits::SetterInput<Owned> for Reader<'_> {
        fn set_pointer_builder(
            mut pointer: ::capnp::private::layout::PointerBuilder<'_>,
            value: Self,
            canonicalize: bool,
        ) -> ::capnp::Result<()> {
            pointer.set_struct(&value.reader, canonicalize)
        }
    }

    impl<'a> Builder<'a> {
        pub fn into_reader(self) -> Reader<'a> {
            self.builder.into_reader().into()
        }
        pub fn reborrow(&mut self) -> Builder<'_> {
            Builder {
                builder: self.builder.reborrow(),
            }
        }
        pub fn reborrow_as_reader(&self) -> Reader<'_> {
            self.builder.as_reader().into()
        }

        pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
            self.builder.as_reader().total_size()
        }
        #[inline]
        pub fn get_join_id(self) -> u32 {
            self.builder.get_data_field::<u32>(0)
        }
        #[inline]
        pub fn set_join_id(&mut self, value: u32) {
            self.builder.set_data_field::<u32>(0, value);
        }
    }

    pub struct Pipeline {
        _typeless: ::capnp::any_pointer::Pipeline,
    }
    impl ::capnp::capability::FromTypelessPipeline for Pipeline {
        fn new(typeless: ::capnp::any_pointer::Pipeline) -> Self {
            Self {
                _typeless: typeless,
            }
        }
    }
    impl Pipeline {}
    mod _private {
        pub(crate) static ENCODED_NODE: [::capnp::Word; 33] = ::capnp::word_array([
            *b"\x00\x00\x00\x00\x05\x00\x06\x00",
            *b"\x17\x98\xf3\xc5\xa9\x09\x8d\xb8",
            *b"\x13\x00\x00\x00\x01\x00\x01\x00",
            *b"\xa1\xf2\xda\x5c\x88\xc7\x84\xa1",
            *b"\x00\x00\x07\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x15\x00\x00\x00\xfa\x00\x00\x00",
            *b"!\x00\x00\x00\x07\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x1d\x00\x00\x00?\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"rpc-twop",
            *b"arty.cap",
            *b"np:Provi",
            *b"sionId\x00\x00",
            *b"\x00\x00\x00\x00\x01\x00\x01\x00",
            *b"\x04\x00\x00\x00\x03\x00\x04\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x01\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x0d\x00\x00\x00:\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x08\x00\x00\x00\x03\x00\x01\x00",
            *b"\x14\x00\x00\x00\x02\x00\x01\x00",
            *b"joinId\x00\x00",
            *b"\x08\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x08\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
        ]);
        pub(crate) fn get_field_types(index: u16) -> ::capnp::introspect::Type {
            match index {
                0 => <u32 as ::capnp::introspect::Introspect>::introspect(),
                _ => ::capnp::introspect::panic_invalid_field_index(index),
            }
        }
        pub(crate) fn get_annotation_types(
            child_index: Option<u16>,
            index: u32,
        ) -> ::capnp::introspect::Type {
            ::capnp::introspect::panic_invalid_annotation_indices(child_index, index)
        }
        pub(crate) static ARENA: ::capnp::private::arena::GeneratedCodeArena =
            ::capnp::private::arena::GeneratedCodeArena::new(&ENCODED_NODE);
        pub(crate) static RAW_SCHEMA: ::capnp::introspect::RawStructSchema =
            ::capnp::introspect::RawStructSchema::new(
                &ARENA,
                NONUNION_MEMBERS,
                MEMBERS_BY_DISCRIMINANT,
                MEMBERS_BY_NAME,
            );
        pub(crate) static NONUNION_MEMBERS: &[u16] = &[0];
        pub(crate) static MEMBERS_BY_DISCRIMINANT: &[u16] = &[];
        pub(crate) static MEMBERS_BY_NAME: &[u16] = &[0];
        pub(crate) const TYPE_ID: u64 = 0xb88d_09a9_c5f3_9817;
    }
}

pub mod recipient_id {
    #[derive(Copy, Clone)]
    pub struct Owned(());
    impl ::capnp::introspect::Introspect for Owned {
        fn introspect() -> ::capnp::introspect::Type {
            ::capnp::introspect::TypeVariant::Struct(::capnp::introspect::RawBrandedStructSchema {
                generic: &_private::RAW_SCHEMA,
                field_types: _private::get_field_types,
                annotation_types: _private::get_annotation_types,
            })
            .into()
        }
    }
    impl ::capnp::traits::Owned for Owned {
        type Reader<'a> = Reader<'a>;
        type Builder<'a> = Builder<'a>;
    }
    impl ::capnp::traits::OwnedStruct for Owned {
        type Reader<'a> = Reader<'a>;
        type Builder<'a> = Builder<'a>;
    }
    impl ::capnp::traits::Pipelined for Owned {
        type Pipeline = Pipeline;
    }

    pub struct Reader<'a> {
        reader: ::capnp::private::layout::StructReader<'a>,
    }
    impl ::core::marker::Copy for Reader<'_> {}
    impl ::core::clone::Clone for Reader<'_> {
        fn clone(&self) -> Self {
            *self
        }
    }

    impl ::capnp::traits::HasTypeId for Reader<'_> {
        const TYPE_ID: u64 = _private::TYPE_ID;
    }
    impl<'a> ::core::convert::From<::capnp::private::layout::StructReader<'a>> for Reader<'a> {
        fn from(reader: ::capnp::private::layout::StructReader<'a>) -> Self {
            Self { reader }
        }
    }

    impl<'a> ::core::convert::From<Reader<'a>> for ::capnp::dynamic_value::Reader<'a> {
        fn from(reader: Reader<'a>) -> Self {
            Self::Struct(::capnp::dynamic_struct::Reader::new(
                reader.reader,
                ::capnp::schema::StructSchema::new(::capnp::introspect::RawBrandedStructSchema {
                    generic: &_private::RAW_SCHEMA,
                    field_types: _private::get_field_types,
                    annotation_types: _private::get_annotation_types,
                }),
            ))
        }
    }

    impl ::core::fmt::Debug for Reader<'_> {
        fn fmt(
            &self,
            f: &mut ::core::fmt::Formatter<'_>,
        ) -> ::core::result::Result<(), ::core::fmt::Error> {
            core::fmt::Debug::fmt(
                &::core::convert::Into::<::capnp::dynamic_value::Reader<'_>>::into(*self),
                f,
            )
        }
    }

    impl<'a> ::capnp::traits::FromPointerReader<'a> for Reader<'a> {
        fn get_from_pointer(
            reader: &::capnp::private::layout::PointerReader<'a>,
            default: ::core::option::Option<&'a [::capnp::Word]>,
        ) -> ::capnp::Result<Self> {
            ::core::result::Result::Ok(reader.get_struct(default)?.into())
        }
    }

    impl<'a> ::capnp::traits::IntoInternalStructReader<'a> for Reader<'a> {
        fn into_internal_struct_reader(self) -> ::capnp::private::layout::StructReader<'a> {
            self.reader
        }
    }

    impl<'a> ::capnp::traits::Imbue<'a> for Reader<'a> {
        fn imbue(&mut self, cap_table: &'a ::capnp::private::layout::CapTable) {
            self.reader
                .imbue(::capnp::private::layout::CapTableReader::Plain(cap_table))
        }
    }

    impl Reader<'_> {
        pub fn reborrow(&self) -> Reader<'_> {
            Self { ..*self }
        }

        pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
            self.reader.total_size()
        }
    }

    pub struct Builder<'a> {
        builder: ::capnp::private::layout::StructBuilder<'a>,
    }
    impl ::capnp::traits::HasStructSize for Builder<'_> {
        const STRUCT_SIZE: ::capnp::private::layout::StructSize =
            ::capnp::private::layout::StructSize {
                data: 0,
                pointers: 0,
            };
    }
    impl ::capnp::traits::HasTypeId for Builder<'_> {
        const TYPE_ID: u64 = _private::TYPE_ID;
    }
    impl<'a> ::core::convert::From<::capnp::private::layout::StructBuilder<'a>> for Builder<'a> {
        fn from(builder: ::capnp::private::layout::StructBuilder<'a>) -> Self {
            Self { builder }
        }
    }

    impl<'a> ::core::convert::From<Builder<'a>> for ::capnp::dynamic_value::Builder<'a> {
        fn from(builder: Builder<'a>) -> Self {
            Self::Struct(::capnp::dynamic_struct::Builder::new(
                builder.builder,
                ::capnp::schema::StructSchema::new(::capnp::introspect::RawBrandedStructSchema {
                    generic: &_private::RAW_SCHEMA,
                    field_types: _private::get_field_types,
                    annotation_types: _private::get_annotation_types,
                }),
            ))
        }
    }

    impl<'a> ::capnp::traits::ImbueMut<'a> for Builder<'a> {
        fn imbue_mut(&mut self, cap_table: &'a mut ::capnp::private::layout::CapTable) {
            self.builder
                .imbue(::capnp::private::layout::CapTableBuilder::Plain(cap_table))
        }
    }

    impl<'a> ::capnp::traits::FromPointerBuilder<'a> for Builder<'a> {
        fn init_pointer(builder: ::capnp::private::layout::PointerBuilder<'a>, _size: u32) -> Self {
            builder
                .init_struct(<Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE)
                .into()
        }
        fn get_from_pointer(
            builder: ::capnp::private::layout::PointerBuilder<'a>,
            default: ::core::option::Option<&'a [::capnp::Word]>,
        ) -> ::capnp::Result<Self> {
            ::core::result::Result::Ok(
                builder
                    .get_struct(
                        <Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE,
                        default,
                    )?
                    .into(),
            )
        }
    }

    impl ::capnp::traits::SetterInput<Owned> for Reader<'_> {
        fn set_pointer_builder(
            mut pointer: ::capnp::private::layout::PointerBuilder<'_>,
            value: Self,
            canonicalize: bool,
        ) -> ::capnp::Result<()> {
            pointer.set_struct(&value.reader, canonicalize)
        }
    }

    impl<'a> Builder<'a> {
        pub fn into_reader(self) -> Reader<'a> {
            self.builder.into_reader().into()
        }
        pub fn reborrow(&mut self) -> Builder<'_> {
            Builder {
                builder: self.builder.reborrow(),
            }
        }
        pub fn reborrow_as_reader(&self) -> Reader<'_> {
            self.builder.as_reader().into()
        }

        pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
            self.builder.as_reader().total_size()
        }
    }

    pub struct Pipeline {
        _typeless: ::capnp::any_pointer::Pipeline,
    }
    impl ::capnp::capability::FromTypelessPipeline for Pipeline {
        fn new(typeless: ::capnp::any_pointer::Pipeline) -> Self {
            Self {
                _typeless: typeless,
            }
        }
    }
    impl Pipeline {}
    mod _private {
        pub(crate) static ENCODED_NODE: [::capnp::Word; 17] = ::capnp::word_array([
            *b"\x00\x00\x00\x00\x05\x00\x06\x00",
            *b"\xc1\x82@\xfd\xb6\x89\xf3\x89",
            *b"\x13\x00\x00\x00\x01\x00\x00\x00",
            *b"\xa1\xf2\xda\x5c\x88\xc7\x84\xa1",
            *b"\x00\x00\x07\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x15\x00\x00\x00\xfa\x00\x00\x00",
            *b"!\x00\x00\x00\x07\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"rpc-twop",
            *b"arty.cap",
            *b"np:Recip",
            *b"ientId\x00\x00",
            *b"\x00\x00\x00\x00\x01\x00\x01\x00",
        ]);
        pub(crate) fn get_field_types(index: u16) -> ::capnp::introspect::Type {
            ::capnp::introspect::panic_invalid_field_index(index)
        }
        pub(crate) fn get_annotation_types(
            child_index: Option<u16>,
            index: u32,
        ) -> ::capnp::introspect::Type {
            ::capnp::introspect::panic_invalid_annotation_indices(child_index, index)
        }
        pub(crate) static ARENA: ::capnp::private::arena::GeneratedCodeArena =
            ::capnp::private::arena::GeneratedCodeArena::new(&ENCODED_NODE);
        pub(crate) static RAW_SCHEMA: ::capnp::introspect::RawStructSchema =
            ::capnp::introspect::RawStructSchema::new(
                &ARENA,
                NONUNION_MEMBERS,
                MEMBERS_BY_DISCRIMINANT,
                MEMBERS_BY_NAME,
            );
        pub(crate) static NONUNION_MEMBERS: &[u16] = &[];
        pub(crate) static MEMBERS_BY_DISCRIMINANT: &[u16] = &[];
        pub(crate) static MEMBERS_BY_NAME: &[u16] = &[];
        pub(crate) const TYPE_ID: u64 = 0x89f3_89b6_fd40_82c1;
    }
}

pub mod third_party_cap_id {
    #[derive(Copy, Clone)]
    pub struct Owned(());
    impl ::capnp::introspect::Introspect for Owned {
        fn introspect() -> ::capnp::introspect::Type {
            ::capnp::introspect::TypeVariant::Struct(::capnp::introspect::RawBrandedStructSchema {
                generic: &_private::RAW_SCHEMA,
                field_types: _private::get_field_types,
                annotation_types: _private::get_annotation_types,
            })
            .into()
        }
    }
    impl ::capnp::traits::Owned for Owned {
        type Reader<'a> = Reader<'a>;
        type Builder<'a> = Builder<'a>;
    }
    impl ::capnp::traits::OwnedStruct for Owned {
        type Reader<'a> = Reader<'a>;
        type Builder<'a> = Builder<'a>;
    }
    impl ::capnp::traits::Pipelined for Owned {
        type Pipeline = Pipeline;
    }

    pub struct Reader<'a> {
        reader: ::capnp::private::layout::StructReader<'a>,
    }
    impl ::core::marker::Copy for Reader<'_> {}
    impl ::core::clone::Clone for Reader<'_> {
        fn clone(&self) -> Self {
            *self
        }
    }

    impl ::capnp::traits::HasTypeId for Reader<'_> {
        const TYPE_ID: u64 = _private::TYPE_ID;
    }
    impl<'a> ::core::convert::From<::capnp::private::layout::StructReader<'a>> for Reader<'a> {
        fn from(reader: ::capnp::private::layout::StructReader<'a>) -> Self {
            Self { reader }
        }
    }

    impl<'a> ::core::convert::From<Reader<'a>> for ::capnp::dynamic_value::Reader<'a> {
        fn from(reader: Reader<'a>) -> Self {
            Self::Struct(::capnp::dynamic_struct::Reader::new(
                reader.reader,
                ::capnp::schema::StructSchema::new(::capnp::introspect::RawBrandedStructSchema {
                    generic: &_private::RAW_SCHEMA,
                    field_types: _private::get_field_types,
                    annotation_types: _private::get_annotation_types,
                }),
            ))
        }
    }

    impl ::core::fmt::Debug for Reader<'_> {
        fn fmt(
            &self,
            f: &mut ::core::fmt::Formatter<'_>,
        ) -> ::core::result::Result<(), ::core::fmt::Error> {
            core::fmt::Debug::fmt(
                &::core::convert::Into::<::capnp::dynamic_value::Reader<'_>>::into(*self),
                f,
            )
        }
    }

    impl<'a> ::capnp::traits::FromPointerReader<'a> for Reader<'a> {
        fn get_from_pointer(
            reader: &::capnp::private::layout::PointerReader<'a>,
            default: ::core::option::Option<&'a [::capnp::Word]>,
        ) -> ::capnp::Result<Self> {
            ::core::result::Result::Ok(reader.get_struct(default)?.into())
        }
    }

    impl<'a> ::capnp::traits::IntoInternalStructReader<'a> for Reader<'a> {
        fn into_internal_struct_reader(self) -> ::capnp::private::layout::StructReader<'a> {
            self.reader
        }
    }

    impl<'a> ::capnp::traits::Imbue<'a> for Reader<'a> {
        fn imbue(&mut self, cap_table: &'a ::capnp::private::layout::CapTable) {
            self.reader
                .imbue(::capnp::private::layout::CapTableReader::Plain(cap_table))
        }
    }

    impl Reader<'_> {
        pub fn reborrow(&self) -> Reader<'_> {
            Self { ..*self }
        }

        pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
            self.reader.total_size()
        }
    }

    pub struct Builder<'a> {
        builder: ::capnp::private::layout::StructBuilder<'a>,
    }
    impl ::capnp::traits::HasStructSize for Builder<'_> {
        const STRUCT_SIZE: ::capnp::private::layout::StructSize =
            ::capnp::private::layout::StructSize {
                data: 0,
                pointers: 0,
            };
    }
    impl ::capnp::traits::HasTypeId for Builder<'_> {
        const TYPE_ID: u64 = _private::TYPE_ID;
    }
    impl<'a> ::core::convert::From<::capnp::private::layout::StructBuilder<'a>> for Builder<'a> {
        fn from(builder: ::capnp::private::layout::StructBuilder<'a>) -> Self {
            Self { builder }
        }
    }

    impl<'a> ::core::convert::From<Builder<'a>> for ::capnp::dynamic_value::Builder<'a> {
        fn from(builder: Builder<'a>) -> Self {
            Self::Struct(::capnp::dynamic_struct::Builder::new(
                builder.builder,
                ::capnp::schema::StructSchema::new(::capnp::introspect::RawBrandedStructSchema {
                    generic: &_private::RAW_SCHEMA,
                    field_types: _private::get_field_types,
                    annotation_types: _private::get_annotation_types,
                }),
            ))
        }
    }

    impl<'a> ::capnp::traits::ImbueMut<'a> for Builder<'a> {
        fn imbue_mut(&mut self, cap_table: &'a mut ::capnp::private::layout::CapTable) {
            self.builder
                .imbue(::capnp::private::layout::CapTableBuilder::Plain(cap_table))
        }
    }

    impl<'a> ::capnp::traits::FromPointerBuilder<'a> for Builder<'a> {
        fn init_pointer(builder: ::capnp::private::layout::PointerBuilder<'a>, _size: u32) -> Self {
            builder
                .init_struct(<Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE)
                .into()
        }
        fn get_from_pointer(
            builder: ::capnp::private::layout::PointerBuilder<'a>,
            default: ::core::option::Option<&'a [::capnp::Word]>,
        ) -> ::capnp::Result<Self> {
            ::core::result::Result::Ok(
                builder
                    .get_struct(
                        <Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE,
                        default,
                    )?
                    .into(),
            )
        }
    }

    impl ::capnp::traits::SetterInput<Owned> for Reader<'_> {
        fn set_pointer_builder(
            mut pointer: ::capnp::private::layout::PointerBuilder<'_>,
            value: Self,
            canonicalize: bool,
        ) -> ::capnp::Result<()> {
            pointer.set_struct(&value.reader, canonicalize)
        }
    }

    impl<'a> Builder<'a> {
        pub fn into_reader(self) -> Reader<'a> {
            self.builder.into_reader().into()
        }
        pub fn reborrow(&mut self) -> Builder<'_> {
            Builder {
                builder: self.builder.reborrow(),
            }
        }
        pub fn reborrow_as_reader(&self) -> Reader<'_> {
            self.builder.as_reader().into()
        }

        pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
            self.builder.as_reader().total_size()
        }
    }

    pub struct Pipeline {
        _typeless: ::capnp::any_pointer::Pipeline,
    }
    impl ::capnp::capability::FromTypelessPipeline for Pipeline {
        fn new(typeless: ::capnp::any_pointer::Pipeline) -> Self {
            Self {
                _typeless: typeless,
            }
        }
    }
    impl Pipeline {}
    mod _private {
        pub(crate) static ENCODED_NODE: [::capnp::Word; 18] = ::capnp::word_array([
            *b"\x00\x00\x00\x00\x05\x00\x06\x00",
            *b"\x9d\xb5,gyI\x7f\xb4",
            *b"\x13\x00\x00\x00\x01\x00\x00\x00",
            *b"\xa1\xf2\xda\x5c\x88\xc7\x84\xa1",
            *b"\x00\x00\x07\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x15\x00\x00\x00\x1a\x01\x00\x00",
            *b"%\x00\x00\x00\x07\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"rpc-twop",
            *b"arty.cap",
            *b"np:Third",
            *b"PartyCap",
            *b"Id\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x01\x00\x01\x00",
        ]);
        pub(crate) fn get_field_types(index: u16) -> ::capnp::introspect::Type {
            ::capnp::introspect::panic_invalid_field_index(index)
        }
        pub(crate) fn get_annotation_types(
            child_index: Option<u16>,
            index: u32,
        ) -> ::capnp::introspect::Type {
            ::capnp::introspect::panic_invalid_annotation_indices(child_index, index)
        }
        pub(crate) static ARENA: ::capnp::private::arena::GeneratedCodeArena =
            ::capnp::private::arena::GeneratedCodeArena::new(&ENCODED_NODE);
        pub(crate) static RAW_SCHEMA: ::capnp::introspect::RawStructSchema =
            ::capnp::introspect::RawStructSchema::new(
                &ARENA,
                NONUNION_MEMBERS,
                MEMBERS_BY_DISCRIMINANT,
                MEMBERS_BY_NAME,
            );
        pub(crate) static NONUNION_MEMBERS: &[u16] = &[];
        pub(crate) static MEMBERS_BY_DISCRIMINANT: &[u16] = &[];
        pub(crate) static MEMBERS_BY_NAME: &[u16] = &[];
        pub(crate) const TYPE_ID: u64 = 0xb47f_4979_672c_b59d;
    }
}

pub mod join_key_part {
    #[derive(Copy, Clone)]
    pub struct Owned(());
    impl ::capnp::introspect::Introspect for Owned {
        fn introspect() -> ::capnp::introspect::Type {
            ::capnp::introspect::TypeVariant::Struct(::capnp::introspect::RawBrandedStructSchema {
                generic: &_private::RAW_SCHEMA,
                field_types: _private::get_field_types,
                annotation_types: _private::get_annotation_types,
            })
            .into()
        }
    }
    impl ::capnp::traits::Owned for Owned {
        type Reader<'a> = Reader<'a>;
        type Builder<'a> = Builder<'a>;
    }
    impl ::capnp::traits::OwnedStruct for Owned {
        type Reader<'a> = Reader<'a>;
        type Builder<'a> = Builder<'a>;
    }
    impl ::capnp::traits::Pipelined for Owned {
        type Pipeline = Pipeline;
    }

    pub struct Reader<'a> {
        reader: ::capnp::private::layout::StructReader<'a>,
    }
    impl ::core::marker::Copy for Reader<'_> {}
    impl ::core::clone::Clone for Reader<'_> {
        fn clone(&self) -> Self {
            *self
        }
    }

    impl ::capnp::traits::HasTypeId for Reader<'_> {
        const TYPE_ID: u64 = _private::TYPE_ID;
    }
    impl<'a> ::core::convert::From<::capnp::private::layout::StructReader<'a>> for Reader<'a> {
        fn from(reader: ::capnp::private::layout::StructReader<'a>) -> Self {
            Self { reader }
        }
    }

    impl<'a> ::core::convert::From<Reader<'a>> for ::capnp::dynamic_value::Reader<'a> {
        fn from(reader: Reader<'a>) -> Self {
            Self::Struct(::capnp::dynamic_struct::Reader::new(
                reader.reader,
                ::capnp::schema::StructSchema::new(::capnp::introspect::RawBrandedStructSchema {
                    generic: &_private::RAW_SCHEMA,
                    field_types: _private::get_field_types,
                    annotation_types: _private::get_annotation_types,
                }),
            ))
        }
    }

    impl ::core::fmt::Debug for Reader<'_> {
        fn fmt(
            &self,
            f: &mut ::core::fmt::Formatter<'_>,
        ) -> ::core::result::Result<(), ::core::fmt::Error> {
            core::fmt::Debug::fmt(
                &::core::convert::Into::<::capnp::dynamic_value::Reader<'_>>::into(*self),
                f,
            )
        }
    }

    impl<'a> ::capnp::traits::FromPointerReader<'a> for Reader<'a> {
        fn get_from_pointer(
            reader: &::capnp::private::layout::PointerReader<'a>,
            default: ::core::option::Option<&'a [::capnp::Word]>,
        ) -> ::capnp::Result<Self> {
            ::core::result::Result::Ok(reader.get_struct(default)?.into())
        }
    }

    impl<'a> ::capnp::traits::IntoInternalStructReader<'a> for Reader<'a> {
        fn into_internal_struct_reader(self) -> ::capnp::private::layout::StructReader<'a> {
            self.reader
        }
    }

    impl<'a> ::capnp::traits::Imbue<'a> for Reader<'a> {
        fn imbue(&mut self, cap_table: &'a ::capnp::private::layout::CapTable) {
            self.reader
                .imbue(::capnp::private::layout::CapTableReader::Plain(cap_table))
        }
    }

    impl Reader<'_> {
        pub fn reborrow(&self) -> Reader<'_> {
            Self { ..*self }
        }

        pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
            self.reader.total_size()
        }
        #[inline]
        pub fn get_join_id(self) -> u32 {
            self.reader.get_data_field::<u32>(0)
        }
        #[inline]
        pub fn get_part_count(self) -> u16 {
            self.reader.get_data_field::<u16>(2)
        }
        #[inline]
        pub fn get_part_num(self) -> u16 {
            self.reader.get_data_field::<u16>(3)
        }
    }

    pub struct Builder<'a> {
        builder: ::capnp::private::layout::StructBuilder<'a>,
    }
    impl ::capnp::traits::HasStructSize for Builder<'_> {
        const STRUCT_SIZE: ::capnp::private::layout::StructSize =
            ::capnp::private::layout::StructSize {
                data: 1,
                pointers: 0,
            };
    }
    impl ::capnp::traits::HasTypeId for Builder<'_> {
        const TYPE_ID: u64 = _private::TYPE_ID;
    }
    impl<'a> ::core::convert::From<::capnp::private::layout::StructBuilder<'a>> for Builder<'a> {
        fn from(builder: ::capnp::private::layout::StructBuilder<'a>) -> Self {
            Self { builder }
        }
    }

    impl<'a> ::core::convert::From<Builder<'a>> for ::capnp::dynamic_value::Builder<'a> {
        fn from(builder: Builder<'a>) -> Self {
            Self::Struct(::capnp::dynamic_struct::Builder::new(
                builder.builder,
                ::capnp::schema::StructSchema::new(::capnp::introspect::RawBrandedStructSchema {
                    generic: &_private::RAW_SCHEMA,
                    field_types: _private::get_field_types,
                    annotation_types: _private::get_annotation_types,
                }),
            ))
        }
    }

    impl<'a> ::capnp::traits::ImbueMut<'a> for Builder<'a> {
        fn imbue_mut(&mut self, cap_table: &'a mut ::capnp::private::layout::CapTable) {
            self.builder
                .imbue(::capnp::private::layout::CapTableBuilder::Plain(cap_table))
        }
    }

    impl<'a> ::capnp::traits::FromPointerBuilder<'a> for Builder<'a> {
        fn init_pointer(builder: ::capnp::private::layout::PointerBuilder<'a>, _size: u32) -> Self {
            builder
                .init_struct(<Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE)
                .into()
        }
        fn get_from_pointer(
            builder: ::capnp::private::layout::PointerBuilder<'a>,
            default: ::core::option::Option<&'a [::capnp::Word]>,
        ) -> ::capnp::Result<Self> {
            ::core::result::Result::Ok(
                builder
                    .get_struct(
                        <Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE,
                        default,
                    )?
                    .into(),
            )
        }
    }

    impl ::capnp::traits::SetterInput<Owned> for Reader<'_> {
        fn set_pointer_builder(
            mut pointer: ::capnp::private::layout::PointerBuilder<'_>,
            value: Self,
            canonicalize: bool,
        ) -> ::capnp::Result<()> {
            pointer.set_struct(&value.reader, canonicalize)
        }
    }

    impl<'a> Builder<'a> {
        pub fn into_reader(self) -> Reader<'a> {
            self.builder.into_reader().into()
        }
        pub fn reborrow(&mut self) -> Builder<'_> {
            Builder {
                builder: self.builder.reborrow(),
            }
        }
        pub fn reborrow_as_reader(&self) -> Reader<'_> {
            self.builder.as_reader().into()
        }

        pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
            self.builder.as_reader().total_size()
        }
        #[inline]
        pub fn get_join_id(self) -> u32 {
            self.builder.get_data_field::<u32>(0)
        }
        #[inline]
        pub fn set_join_id(&mut self, value: u32) {
            self.builder.set_data_field::<u32>(0, value);
        }
        #[inline]
        pub fn get_part_count(self) -> u16 {
            self.builder.get_data_field::<u16>(2)
        }
        #[inline]
        pub fn set_part_count(&mut self, value: u16) {
            self.builder.set_data_field::<u16>(2, value);
        }
        #[inline]
        pub fn get_part_num(self) -> u16 {
            self.builder.get_data_field::<u16>(3)
        }
        #[inline]
        pub fn set_part_num(&mut self, value: u16) {
            self.builder.set_data_field::<u16>(3, value);
        }
    }

    pub struct Pipeline {
        _typeless: ::capnp::any_pointer::Pipeline,
    }
    impl ::capnp::capability::FromTypelessPipeline for Pipeline {
        fn new(typeless: ::capnp::any_pointer::Pipeline) -> Self {
            Self {
                _typeless: typeless,
            }
        }
    }
    impl Pipeline {}
    mod _private {
        pub(crate) static ENCODED_NODE: [::capnp::Word; 64] = ::capnp::word_array([
            *b"\x00\x00\x00\x00\x05\x00\x06\x00",
            *b"\x83\xca\x7f\x09Y\x90\xb2\x95",
            *b"\x13\x00\x00\x00\x01\x00\x01\x00",
            *b"\xa1\xf2\xda\x5c\x88\xc7\x84\xa1",
            *b"\x00\x00\x07\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x15\x00\x00\x00\xfa\x00\x00\x00",
            *b"!\x00\x00\x00\x07\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x1d\x00\x00\x00\xaf\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"rpc-twop",
            *b"arty.cap",
            *b"np:JoinK",
            *b"eyPart\x00\x00",
            *b"\x00\x00\x00\x00\x01\x00\x01\x00",
            *b"\x0c\x00\x00\x00\x03\x00\x04\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x01\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"E\x00\x00\x00:\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"@\x00\x00\x00\x03\x00\x01\x00",
            *b"L\x00\x00\x00\x02\x00\x01\x00",
            *b"\x01\x00\x00\x00\x02\x00\x00\x00",
            *b"\x00\x00\x01\x00\x01\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"I\x00\x00\x00R\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"H\x00\x00\x00\x03\x00\x01\x00",
            *b"T\x00\x00\x00\x02\x00\x01\x00",
            *b"\x02\x00\x00\x00\x03\x00\x00\x00",
            *b"\x00\x00\x01\x00\x02\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"Q\x00\x00\x00B\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"L\x00\x00\x00\x03\x00\x01\x00",
            *b"X\x00\x00\x00\x02\x00\x01\x00",
            *b"joinId\x00\x00",
            *b"\x08\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x08\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"partCoun",
            *b"t\x00\x00\x00\x00\x00\x00\x00",
            *b"\x07\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x07\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"partNum\x00",
            *b"\x07\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x07\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
        ]);
        pub(crate) fn get_field_types(index: u16) -> ::capnp::introspect::Type {
            match index {
                0 => <u32 as ::capnp::introspect::Introspect>::introspect(),
                1 => <u16 as ::capnp::introspect::Introspect>::introspect(),
                2 => <u16 as ::capnp::introspect::Introspect>::introspect(),
                _ => ::capnp::introspect::panic_invalid_field_index(index),
            }
        }
        pub(crate) fn get_annotation_types(
            child_index: Option<u16>,
            index: u32,
        ) -> ::capnp::introspect::Type {
            ::capnp::introspect::panic_invalid_annotation_indices(child_index, index)
        }
        pub(crate) static ARENA: ::capnp::private::arena::GeneratedCodeArena =
            ::capnp::private::arena::GeneratedCodeArena::new(&ENCODED_NODE);
        pub(crate) static RAW_SCHEMA: ::capnp::introspect::RawStructSchema =
            ::capnp::introspect::RawStructSchema::new(
                &ARENA,
                NONUNION_MEMBERS,
                MEMBERS_BY_DISCRIMINANT,
                MEMBERS_BY_NAME,
            );
        pub(crate) static NONUNION_MEMBERS: &[u16] = &[0, 1, 2];
        pub(crate) static MEMBERS_BY_DISCRIMINANT: &[u16] = &[];
        pub(crate) static MEMBERS_BY_NAME: &[u16] = &[0, 1, 2];
        pub(crate) const TYPE_ID: u64 = 0x95b2_9059_097f_ca83;
    }
}

pub mod join_result {
    #[derive(Copy, Clone)]
    pub struct Owned(());
    impl ::capnp::introspect::Introspect for Owned {
        fn introspect() -> ::capnp::introspect::Type {
            ::capnp::introspect::TypeVariant::Struct(::capnp::introspect::RawBrandedStructSchema {
                generic: &_private::RAW_SCHEMA,
                field_types: _private::get_field_types,
                annotation_types: _private::get_annotation_types,
            })
            .into()
        }
    }
    impl ::capnp::traits::Owned for Owned {
        type Reader<'a> = Reader<'a>;
        type Builder<'a> = Builder<'a>;
    }
    impl ::capnp::traits::OwnedStruct for Owned {
        type Reader<'a> = Reader<'a>;
        type Builder<'a> = Builder<'a>;
    }
    impl ::capnp::traits::Pipelined for Owned {
        type Pipeline = Pipeline;
    }

    pub struct Reader<'a> {
        reader: ::capnp::private::layout::StructReader<'a>,
    }
    impl ::core::marker::Copy for Reader<'_> {}
    impl ::core::clone::Clone for Reader<'_> {
        fn clone(&self) -> Self {
            *self
        }
    }

    impl ::capnp::traits::HasTypeId for Reader<'_> {
        const TYPE_ID: u64 = _private::TYPE_ID;
    }
    impl<'a> ::core::convert::From<::capnp::private::layout::StructReader<'a>> for Reader<'a> {
        fn from(reader: ::capnp::private::layout::StructReader<'a>) -> Self {
            Self { reader }
        }
    }

    impl<'a> ::core::convert::From<Reader<'a>> for ::capnp::dynamic_value::Reader<'a> {
        fn from(reader: Reader<'a>) -> Self {
            Self::Struct(::capnp::dynamic_struct::Reader::new(
                reader.reader,
                ::capnp::schema::StructSchema::new(::capnp::introspect::RawBrandedStructSchema {
                    generic: &_private::RAW_SCHEMA,
                    field_types: _private::get_field_types,
                    annotation_types: _private::get_annotation_types,
                }),
            ))
        }
    }

    impl ::core::fmt::Debug for Reader<'_> {
        fn fmt(
            &self,
            f: &mut ::core::fmt::Formatter<'_>,
        ) -> ::core::result::Result<(), ::core::fmt::Error> {
            core::fmt::Debug::fmt(
                &::core::convert::Into::<::capnp::dynamic_value::Reader<'_>>::into(*self),
                f,
            )
        }
    }

    impl<'a> ::capnp::traits::FromPointerReader<'a> for Reader<'a> {
        fn get_from_pointer(
            reader: &::capnp::private::layout::PointerReader<'a>,
            default: ::core::option::Option<&'a [::capnp::Word]>,
        ) -> ::capnp::Result<Self> {
            ::core::result::Result::Ok(reader.get_struct(default)?.into())
        }
    }

    impl<'a> ::capnp::traits::IntoInternalStructReader<'a> for Reader<'a> {
        fn into_internal_struct_reader(self) -> ::capnp::private::layout::StructReader<'a> {
            self.reader
        }
    }

    impl<'a> ::capnp::traits::Imbue<'a> for Reader<'a> {
        fn imbue(&mut self, cap_table: &'a ::capnp::private::layout::CapTable) {
            self.reader
                .imbue(::capnp::private::layout::CapTableReader::Plain(cap_table))
        }
    }

    impl<'a> Reader<'a> {
        pub fn reborrow(&self) -> Reader<'_> {
            Self { ..*self }
        }

        pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
            self.reader.total_size()
        }
        #[inline]
        pub fn get_join_id(self) -> u32 {
            self.reader.get_data_field::<u32>(0)
        }
        #[inline]
        pub fn get_succeeded(self) -> bool {
            self.reader.get_bool_field(32)
        }
        #[inline]
        pub fn get_cap(self) -> ::capnp::any_pointer::Reader<'a> {
            ::capnp::any_pointer::Reader::new(self.reader.get_pointer_field(0))
        }
        #[inline]
        pub fn has_cap(&self) -> bool {
            !self.reader.get_pointer_field(0).is_null()
        }
    }

    pub struct Builder<'a> {
        builder: ::capnp::private::layout::StructBuilder<'a>,
    }
    impl ::capnp::traits::HasStructSize for Builder<'_> {
        const STRUCT_SIZE: ::capnp::private::layout::StructSize =
            ::capnp::private::layout::StructSize {
                data: 1,
                pointers: 1,
            };
    }
    impl ::capnp::traits::HasTypeId for Builder<'_> {
        const TYPE_ID: u64 = _private::TYPE_ID;
    }
    impl<'a> ::core::convert::From<::capnp::private::layout::StructBuilder<'a>> for Builder<'a> {
        fn from(builder: ::capnp::private::layout::StructBuilder<'a>) -> Self {
            Self { builder }
        }
    }

    impl<'a> ::core::convert::From<Builder<'a>> for ::capnp::dynamic_value::Builder<'a> {
        fn from(builder: Builder<'a>) -> Self {
            Self::Struct(::capnp::dynamic_struct::Builder::new(
                builder.builder,
                ::capnp::schema::StructSchema::new(::capnp::introspect::RawBrandedStructSchema {
                    generic: &_private::RAW_SCHEMA,
                    field_types: _private::get_field_types,
                    annotation_types: _private::get_annotation_types,
                }),
            ))
        }
    }

    impl<'a> ::capnp::traits::ImbueMut<'a> for Builder<'a> {
        fn imbue_mut(&mut self, cap_table: &'a mut ::capnp::private::layout::CapTable) {
            self.builder
                .imbue(::capnp::private::layout::CapTableBuilder::Plain(cap_table))
        }
    }

    impl<'a> ::capnp::traits::FromPointerBuilder<'a> for Builder<'a> {
        fn init_pointer(builder: ::capnp::private::layout::PointerBuilder<'a>, _size: u32) -> Self {
            builder
                .init_struct(<Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE)
                .into()
        }
        fn get_from_pointer(
            builder: ::capnp::private::layout::PointerBuilder<'a>,
            default: ::core::option::Option<&'a [::capnp::Word]>,
        ) -> ::capnp::Result<Self> {
            ::core::result::Result::Ok(
                builder
                    .get_struct(
                        <Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE,
                        default,
                    )?
                    .into(),
            )
        }
    }

    impl ::capnp::traits::SetterInput<Owned> for Reader<'_> {
        fn set_pointer_builder(
            mut pointer: ::capnp::private::layout::PointerBuilder<'_>,
            value: Self,
            canonicalize: bool,
        ) -> ::capnp::Result<()> {
            pointer.set_struct(&value.reader, canonicalize)
        }
    }

    impl<'a> Builder<'a> {
        pub fn into_reader(self) -> Reader<'a> {
            self.builder.into_reader().into()
        }
        pub fn reborrow(&mut self) -> Builder<'_> {
            Builder {
                builder: self.builder.reborrow(),
            }
        }
        pub fn reborrow_as_reader(&self) -> Reader<'_> {
            self.builder.as_reader().into()
        }

        pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
            self.builder.as_reader().total_size()
        }
        #[inline]
        pub fn get_join_id(self) -> u32 {
            self.builder.get_data_field::<u32>(0)
        }
        #[inline]
        pub fn set_join_id(&mut self, value: u32) {
            self.builder.set_data_field::<u32>(0, value);
        }
        #[inline]
        pub fn get_succeeded(self) -> bool {
            self.builder.get_bool_field(32)
        }
        #[inline]
        pub fn set_succeeded(&mut self, value: bool) {
            self.builder.set_bool_field(32, value);
        }
        #[inline]
        pub fn get_cap(self) -> ::capnp::any_pointer::Builder<'a> {
            ::capnp::any_pointer::Builder::new(self.builder.get_pointer_field(0))
        }
        #[inline]
        pub fn init_cap(self) -> ::capnp::any_pointer::Builder<'a> {
            let mut result = ::capnp::any_pointer::Builder::new(self.builder.get_pointer_field(0));
            result.clear();
            result
        }
        #[inline]
        pub fn has_cap(&self) -> bool {
            !self.builder.is_pointer_field_null(0)
        }
    }

    pub struct Pipeline {
        _typeless: ::capnp::any_pointer::Pipeline,
    }
    impl ::capnp::capability::FromTypelessPipeline for Pipeline {
        fn new(typeless: ::capnp::any_pointer::Pipeline) -> Self {
            Self {
                _typeless: typeless,
            }
        }
    }
    impl Pipeline {
        pub fn get_cap(&self) -> ::capnp::any_pointer::Pipeline {
            ::capnp::capability::FromTypelessPipeline::new(self._typeless.get_pointer_field(0))
        }
    }
    mod _private {
        pub(crate) static ENCODED_NODE: [::capnp::Word; 64] = ::capnp::word_array([
            *b"\x00\x00\x00\x00\x05\x00\x06\x00",
            *b"\xee\xeb\xb706:&\x9d",
            *b"\x13\x00\x00\x00\x01\x00\x01\x00",
            *b"\xa1\xf2\xda\x5c\x88\xc7\x84\xa1",
            *b"\x01\x00\x07\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x15\x00\x00\x00\xf2\x00\x00\x00",
            *b"!\x00\x00\x00\x07\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x1d\x00\x00\x00\xaf\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"rpc-twop",
            *b"arty.cap",
            *b"np:JoinR",
            *b"esult\x00\x00\x00",
            *b"\x00\x00\x00\x00\x01\x00\x01\x00",
            *b"\x0c\x00\x00\x00\x03\x00\x04\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x01\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"E\x00\x00\x00:\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"@\x00\x00\x00\x03\x00\x01\x00",
            *b"L\x00\x00\x00\x02\x00\x01\x00",
            *b"\x01\x00\x00\x00 \x00\x00\x00",
            *b"\x00\x00\x01\x00\x01\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"I\x00\x00\x00R\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"H\x00\x00\x00\x03\x00\x01\x00",
            *b"T\x00\x00\x00\x02\x00\x01\x00",
            *b"\x02\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x01\x00\x02\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"Q\x00\x00\x00\x22\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"L\x00\x00\x00\x03\x00\x01\x00",
            *b"X\x00\x00\x00\x02\x00\x01\x00",
            *b"joinId\x00\x00",
            *b"\x08\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x08\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"succeede",
            *b"d\x00\x00\x00\x00\x00\x00\x00",
            *b"\x01\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x01\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"cap\x00\x00\x00\x00\x00",
            *b"\x12\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x03\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x12\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
            *b"\x00\x00\x00\x00\x00\x00\x00\x00",
        ]);
        pub(crate) fn get_field_types(index: u16) -> ::capnp::introspect::Type {
            match index {
                0 => <u32 as ::capnp::introspect::Introspect>::introspect(),
                1 => <bool as ::capnp::introspect::Introspect>::introspect(),
                2 => <::capnp::any_pointer::Owned as ::capnp::introspect::Introspect>::introspect(),
                _ => ::capnp::introspect::panic_invalid_field_index(index),
            }
        }
        pub(crate) fn get_annotation_types(
            child_index: Option<u16>,
            index: u32,
        ) -> ::capnp::introspect::Type {
            ::capnp::introspect::panic_invalid_annotation_indices(child_index, index)
        }
        pub(crate) static ARENA: ::capnp::private::arena::GeneratedCodeArena =
            ::capnp::private::arena::GeneratedCodeArena::new(&ENCODED_NODE);
        pub(crate) static RAW_SCHEMA: ::capnp::introspect::RawStructSchema =
            ::capnp::introspect::RawStructSchema::new(
                &ARENA,
                NONUNION_MEMBERS,
                MEMBERS_BY_DISCRIMINANT,
                MEMBERS_BY_NAME,
            );
        pub(crate) static NONUNION_MEMBERS: &[u16] = &[0, 1, 2];
        pub(crate) static MEMBERS_BY_DISCRIMINANT: &[u16] = &[];
        pub(crate) static MEMBERS_BY_NAME: &[u16] = &[2, 0, 1];
        pub(crate) const TYPE_ID: u64 = 0x9d26_3a36_30b7_ebee;
    }
}
