@0xeaa603db5cb0c1e9;

# Some of these come from https://github.com/dariusk/corpora

const corporations : List(Text) = [
		"Wal-Mart Stores",
		"Exxon Mobil",
		"Chevron",
		"Berkshire Hathaway",
		"Apple",
		"Phillips 66",
		"General Motors",
		"Ford Motor",
		"General Electric",
		"Valero Energy",
		"AT&T",
		"CVS Caremark",
		"Fannie Mae",
		"UnitedHealth Group",
		"McKesson",
		"Verizon Communications",
		"Hewlett-Packard",
		"J.P. Morgan Chase & Co.",
		"Costco Wholesale",
		"Express Scripts Holding",
		"Bank of America",
		"Cardinal Health",
		"International Business Machines",
		"Kroger",
		"Marathon Petroleum",
		"Citigroup",
		"Archer Daniels Midland",
		"AmerisourceBergen",
		"Wells Fargo",
		"Boeing",
		"Procter & Gamble",
		"Freddie Mac",
		"Home Depot",
		"Microsoft",
		"Amazon.com",
		"Target",
		"Walgreen Co.",
		"WellPoint",
		"Johnson & Johnson",
		"American International Group",
		"State Farm Insurance Cos.",
		"MetLife",
		"PepsiCo",
		"Comcast",
		"United Technologies",
		"Google",
		"ConocoPhillips",
		"Dow Chemical",
		"Caterpillar",
		"United Parcel Service",
		"Pfizer",
		"Lowe’s Companies",
		"Intel Corporation",
		"Energy Transfer Equity, L.P.",
		"Cisco Systems, Inc.",
		"Enterprise Products Partners L.P.",
		"Aetna Inc.",
		"The Coca-Cola Company",
		"Lockheed Martin Corporation",
		"Best Buy Co., Inc.",
		"The Walt Disney Company",
		"CHS Inc.",
		"Sysco Corporation",
		"FedEx Corporation",
		"Merck & Co., Inc.",
		"INTL FCStone Inc.",
		"Safeway Inc.",
		"Johnson Controls, Inc.",
		"Ingram Micro Inc.",
		"Plains GP Holdings, L.P.",
		"World Fuel Services Corporation",
		"Prudential Financial, Inc.",
		"Humana Inc.",
		"The Goldman Sachs Group, Inc.",
		"Tesoro Corporation",
		"Liberty Mutual Holding Company Inc.",
		"Honeywell International Inc.",
		"United Continental Holdings, Inc.",
		"HCA Holdings, Inc.",
		"Deere & Company",
		"Delta Air Lines, Inc.",
		"Oracle Corporation",
		"Morgan Stanley",
		"Hess Corporation",
		"Twenty-First Century Fox, Inc.",
		"E.I. du Pont de Nemours and Company",
		"Sears Holdings Corporation",
		"New York Life Insurance Company",
		"Mondelez International, Inc.",
		"American Express Company",
		"Nationwide Mutual Insurance Co.",
		"The Allstate Corporation",
		"Tyson Foods, Inc.",
		"Supervalu Inc.",
		"TIAA-CREF",
		"Massachusetts Mutual Life Insurance Company",
		"CIGNA Corporation",
		"DIRECTV",
		"General Dynamics Corporation",
		"Philip Morris International Inc.",
		"3M Company",
		"Time Warner Inc.",
		"Halliburton Company",
		"Publix Super Markets, Inc.",
		"International Paper Company",
		"McDonald’s Corporation",
		"Macy’s, Inc.",
		"The TJX Companies, Inc.",
		"Fluor Corporation",
		"Northwestern Mutual Life Insurance Company,Inc.",
		"Tech Data Corporation",
		"American Airlines Group Inc.",
		"The Hartford Financial Services Group, Inc.",
		"The Travelers Companies, Inc.",
		"Nike, Inc.",
		"Occidental Petroleum Corporation",
		"Avnet, Inc.",
		"Rite Aid Corporation",
		"Exelon Corporation",
		"Qualcomm Incorporated",
		"Emerson Electric Co.",
		"Northrop Grumman Corporation",
		"Duke Energy Corporation",
		"Capital One Financial Corporation",
		"Aflac Incorporated",
		"Raytheon Company",
		"Staples, Inc.",
		"EMC Corporation",
		"Eli Lilly and Company",
		"Alcoa Inc.",
		"National Oilwell Varco, Inc.",
		"Baker Hughes Incorporated",
		"US Foods, Inc.",
		"Time Warner Cable Inc.",
		"Union Pacific Corporation",
		"Abbott Laboratories",
		"Xerox Corporation",
		"Arrow Electronics, Inc",
		"Kimberly-Clark Corporation",
		"U.S. Bancorp",
		"United Services Automobile Association",
		"Freeport-McMoRan Copper & Gold Inc.",
		"Icahn Enterprises L.P.",
		"ManpowerGroup Inc.",
		"HollyFrontier Corporation",
		"Global Partners LP",
		"The Goodyear Tire & Rubber Company",
		"PBF Energy Inc.",
		"Danaher Corporation",
		"Nucor Corporation",
		"Kohl’s Corporation",
		"AbbVie Inc.",
		"Whirlpool Corporation",
		"Amgen Inc.",
		"Jabil Circuit, Inc.",
		"Kraft Foods Group, Inc.",
		"The Progressive Corporation",
		"CenturyLink, Inc.",
		"General Mills, Inc.",
		"Southwest Airlines Co.",
		"Altria Group, Inc.",
		"AutoNation, Inc.",
		"Chesapeake Energy Corporation",
		"Dollar General Corporation",
		"TRW Automotive Holdings Corp.",
		"United States Steel Corporation",
		"Colgate-Palmolive Company",
		"Cummins Inc.",
		"PACCAR Inc",
		"The Southern Company",
		"Illinois Tool Works Inc.",
		"The PNC Financial Services Group, Inc.",
		"Medtronic, Inc.",
		"The AES Corporation",
		"Murphy USA Inc.",
		"Bristol-Myers Squibb Company",
		"Lear Corporation",
		"The Gap, Inc.",
		"Apache Corporation",
		"eBay Inc.",
		"The Bank of New York Mellon Corporation",
		"CBS Corporation",
		"PG&E Corporation",
		"ConAgra Foods, Inc.",
		"Computer Sciences Corporation",
		"American Electric Power Company, Inc.",
		"Western Digital Corporation",
		"Marathon Oil Corporation",
		"Baxter International Inc.",
		"PPG Industries, Inc.",
		"NextEra Energy, Inc.",
		"Community Health Systems, Inc.",
		"Loews Corporation",
		"Penske Automotive Group, Inc.",
		"FirstEnergy Corp.",
		"Starbucks Corporation",
		"Monsanto Company",
		"Kellogg Company",
		"Land O’Lakes, Inc.",
		"ONEOK, Inc.",
		"Omnicom Group Inc.",
		"Anadarko Petroleum Corporation",
		"EOG Resources, Inc.",
		"DISH Network Corporation",
		"Genuine Parts Company",
		"Kinder Morgan, Inc.",
		"Waste Management, Inc.",
		"The Chubb Corporation",
		"Aramark Holdings Corporation",
		"Viacom Inc.",
		"Las Vegas Sands Corp.",
		"Dominion Resources, Inc.",
		"Ecolab Inc.",
		"Smithfield Foods, Inc.",
		"Thermo Fisher Scientific Inc.",
		"Yum! Brands, Inc.",
		"Parker-Hannifin Corporation",
		"Whole Foods Market, Inc.",
		"Marriott International, Inc.",
		"C. H. Robinson Worldwide, Inc.",
		"L-3 Communications Holdings, Inc.",
		"Edison International",
		"Toys “R” Us, Inc.",
		"Nordstrom, Inc.",
		"Consolidated Edison, Inc.",
		"Marsh & McLennan Companies, Inc.",
		"Texas Instruments Incorporated",
		"Textron Inc.",
		"Tenet Healthcare Corporation",
		"DaVita HealthCare Partners Inc.",
		"CSX Corporation",
		"Lincoln National Corporation",
		"Praxair, Inc.",
		"PPL Corporation",
		"J.C. Penney Company, Inc.",
		"Peter Kiewit Sons’, Inc.",
		"Jacobs Engineering Group Inc.",
		"Visa Inc.",
		"H.J. Heinz Company",
		"CarMax, Inc.",
		"V.F. Corporation",
		"Entergy Corporation",
		"Automatic Data Processing, Inc.",
		"NRG Energy, Inc.",
		"Guardian Life Ins. Co. of America",
		"Liberty Interactive Corporation",
		"Norfolk Southern Corporation",
		"Office Depot, Inc.",
		"Ameriprise Financial, Inc.",
		"Gilead Sciences, Inc.",
		"Centene Corporation",
		"Leucadia National Corporation",
		"Huntsman Corporation",
		"Health Net, Inc.",
		"Stanley Black & Decker, Inc.",
		"URS Corporation",
		"Xcel Energy Inc.",
		"Bed Bath & Beyond Inc.",
		"Navistar International Corporation",
		"Synnex Corporation",
		"First Data Corporation",
		"AGCO Corporation",
		"L Brands, Inc.",
		"Hertz Global Holdings, Inc.",
		"CDW Corporation",
		"CST Brands, Inc.",
		"Sempra Energy",
		"R.R. Donnelley & Sons Company",
		"BB&T Corporation",
		"Devon Energy Corporation",
		"Family Dollar Stores, Inc.",
		"Unum Group",
		"Ally Financial Inc.",
		"Reinsurance Group of America, Incorporated",
		"State Street Corporation",
		"Air Products & Chemicals, Inc.",
		"Ross Stores, Inc.",
		"The Sherwin-Williams Company",
		"The Estée Lauder Companies Inc.",
		"BlackRock, Inc.",
		"Western Refining, Inc.",
		"Avon Products, Inc.",
		"The Mosaic Company",
		"Public Service Enterprise Group Incorporated",
		"Dean Foods Company",
		"Cameron International Corporation",
		"MGM Resorts International",
		"KKR & Co. L.P.",
		"Hilton Worldwide Holdings Inc.",
		"DTE Energy Company",
		"Genworth Financial, Inc.",
		"Henry Schein, Inc.",
		"Rock-Tenn Company",
		"WellCare Health Plans, Inc.",
		"W.W. Grainger, Inc.",
		"Discover Financial Services",
		"Eastman Chemical Company",
		"Principal Financial Group, Inc.",
		"Reliance Steel & Aluminum Co.",
		"AutoZone, Inc.",
		"Dover Corporation",
		"Micron Technology, Inc.",
		"Owens & Minor, Inc.",
		"Assurant, Inc.",
		"GameStop Corp.",
		"Stryker Corporation",
		"Group 1 Automotive, Inc.",
		"Cognizant Technology Solutions Corporation",
		"Sonic Automotive, Inc.",
		"Autoliv, Inc.",
		"Hormel Foods Corporation",
		"Motorola Solutions, Inc.",
		"Crown Holdings, Inc.",
		"SunTrust Banks, Inc.",
		"Campbell Soup Company",
		"Fidelity National Financial, Inc.",
		"HD Supply Holdings, Inc.",
		"Caesars Entertainment Corporation",
		"Darden Restaurants, Inc.",
		"Weyerhaeuser Company",
		"Ball Corporation",
		"Precision Castparts Corp.",
		"Masco Corporation",
		"Universal Health Services, Inc.",
		"Republic Services, Inc.",
		"MasterCard Incorporated",
		"Newmont Mining Corporation",
		"Broadcom Corporation",
		"Reynolds American Inc.",
		"PVH Corp.",
		"Charter Communications, Inc.",
		"AECOM Technology Corporation",
		"CenterPoint Energy, Inc.",
		"Pacific Life",
		"Thrivent Financial for Lutherans",
		"Becton, Dickinson and Company",
		"Franklin Resources, Inc.",
		"Tenneco Inc.",
		"TravelCenters of America LLC",
		"Avis Budget Group, Inc.",
		"Facebook, Inc.",
		"Dollar Tree, Inc.",
		"Corning Incorporated",
		"Ashland Inc.",
		"Sealed Air Corporation",
		"Core-Mark Holding Company, Inc.",
		"Oshkosh Corporation",
		"Coca-Cola Enterprises, Inc.",
		"WESCO International, Inc.",
		"Applied Materials, Inc.",
		"Visteon Corporation",
		"BorgWarner Inc.",
		"Spectrum Group International, Inc.",
		"Oaktree Capital Group, LLC",
		"Steel Dynamics, Inc.",
		"Jarden Corporation",
		"Mohawk Industries, Inc.",
		"Terex Corporation",
		"Northeast Utilities",
		"KBR, Inc.",
		"Fifth Third Bancorp",
		"UGI Corporation",
		"CBRE Group, Inc.",
		"Quest Diagnostics Incorporated",
		"Peabody Energy Corporation",
		"The Hershey Company",
		"Boston Scientific Corporation",
		"FMC Technologies, Inc.",
		"The Interpublic Group of Companies, Inc.",
		"Commercial Metals Company",
		"The Pantry, Inc.",
		"Owens-Illinois, Inc.",
		"American Family Ins. Group",
		"Ralph Lauren Corporation",
		"Biogen Idec Inc.",
		"PetSmart, Inc.",
		"Mylan Inc.",
		"Symantec Corporation",
		"Ameren Corporation",
		"The Williams Companies, Inc.",
		"Barnes & Noble, Inc.",
		"Huntington Ingalls Industries, Inc.",
		"The Priceline Group Inc.",
		"Agilent Technologies, Inc.",
		"Dana Holding Corporation",
		"Dillard’s, Inc.",
		"Seaboard Corporation",
		"Vanguard Health Systems, Inc.",
		"Casey’s General Stores, Inc.",
		"O’Reilly Automotive, Inc.",
		"The Blackstone Group L.P.",
		"Mutual of Omaha Insurance Company",
		"Molina Healthcare, Inc.",
		"CMS Energy Corporation",
		"Targa Resources Corp.",
		"Quanta Services, Inc.",
		"Cablevision Systems Corporation",
		"Avery Dennison Corporation",
		"Celanese Corporation",
		"Foot Locker, Inc.",
		"Celgene Corporation",
		"Advance Auto Parts, Inc.",
		"Mattel, Inc.",
		"Live Nation Entertainment, Inc.",
		"General Cable Corporation",
		"Ryder System, Inc.",
		"EMCOR Group, Inc.",
		"Allergan, Inc.",
		"W.R. Berkley Corporation",
		"Rockwell Automation, Inc.",
		"NetApp, Inc.",
		"Ingredion Incorporated",
		"Level 3 Communications, Inc.",
		"Calpine Corporation",
		"Omnicare, Inc.",
		"Erie Insurance Group",
		"SLM Corporation",
		"D.R. Horton, Inc.",
		"CC Media Holdings, Inc.",
		"Anixter International Inc.",
		"Dick’s Sporting Goods, Inc.",
		"SanDisk Corporation",
		"NCR Corporation",
		"Starwood Hotels & Resorts Worldwide, Inc.",
		"Expeditors International of Washington, Inc.",
		"Fidelity National Information Services, Inc.",
		"United Natural Foods, Inc.",
		"Auto-Owners Insurance Group",
		"Windstream Holdings, Inc.",
		"Dr Pepper Snapple Group, Inc.",
		"Lennar Corporation",
		"Sanmina",
		"Harley-Davidson, Inc.",
		"CONSOL Energy Inc.",
		"The J.M. Smucker Company",
		"Newell Rubbermaid Inc.",
		"CH2M HILL Companies, Ltd.",
		"Energy Future Holdings Corp.",
		"Susser Holdings Corporation",
		"Laboratory Corporation of America Holdings",
		"Kindred Healthcare, Inc.",
		"Leidos Holdings Inc.",
		"Booz Allen Hamilton Holding Corp.",
		"The Jones Financial Companies,L.L.L.P.",
		"Cliffs Natural Resources Inc.",
		"PulteGroup, Inc.",
		"Regions Financial Corporation",
		"NiSource Inc.",
		"Graybar Electric Company, Inc.",
		"Integrys Energy Group, Inc.",
		"The Clorox Company",
		"Wynn Resorts, Limited",
		"The Andersons, Inc.",
		"J.B. Hunt Transport Services, Inc.",
		"AK Steel Holding Corporation",
		"Harbinger Group Inc.",
		"MeadWestvaco Corporation",
		"The Western Union Company",
		"The Charles Schwab Corporation",
		"Discovery Communications, Inc.",
		"Spectra Energy Corp",
		"St. Jude Medical, Inc.",
		"CF Industries Holdings, Inc.",
		"Con-way Inc.",
		"Old Republic International Corporation",
		"JetBlue Airways Corporation",
		"Calumet Specialty Products Partners, L.P.",
		"Kelly Services, Inc.",
		"Domtar Corporation",
		"Murphy Oil Corporation",
		"Harris Corporation",
		"Asbury Automotive Group, Inc.",
		"Big Lots, Inc.",
		"Advanced Micro Devices, Inc.",
		"Owens Corning",
		"Realogy Holdings Corp.",
		"Host Hotels & Resorts, Inc.",
		"MRC Global Inc.",
		"Simon Property Group, Inc.",
		"Tractor Supply Company",
		"Gannett Co., Inc.",
		"Alaska Air Group, Inc.",
		"Insight Enterprises, Inc.",
		"McGraw Hill Financial, Inc.",
		"Buckeye Partners, L.P.",
		"Quintiles Transnational Holdings Inc.",
		"American Financial Group, Inc.",
		"United Stationers Inc.",
		"Coach, Inc.",
		"LKQ Corporation",
		"Noble Energy, Inc.",
		"Bemis Company, Inc.",
		"Joy Global Inc.",
		"Wyndham Worldwide Corporation",
		"NII Holdings, Inc.",
		"Lorillard, Inc.",
		"Alleghany Corporation",
		"Airgas, Inc.",
		"First American Financial Corporation",
		"United Rentals, Inc."
];

const scientists :List(Text) = [
        "Aage Bohr",
        "Abdul Qadeer Khan",
        "Abu Nasr Al-Farabi",
        "Ada Lovelace",
        "Adalbert Czerny",
        "Agnes Arber",
        "Ahmed Zewail",
        "Al-Battani",
        "Alan Turing",
        "Albert Abraham Michelson",
        "Albert Einstein",
        "Alberto Santos-Dumont",
        "Albrecht von Haller",
        "Aldo Leopold",
        "Alessandro Volta",
        "Alexander Bain",
        "Alexander Brongniart",
        "Alexander Fleming",
        "Alexander Graham Bell",
        "Alexander Von Humboldt",
        "Alfred Binet",
        "Alfred Blalock",
        "Alfred Kinsey",
        "Alfred Nobel",
        "Alfred Russel Wallace",
        "Alfred Wegener",
        "Amedeo Avogadro",
        "Anders Celsius",
        "Andre Marie Ampère",
        "Andreas Vesalius",
        "Angel Alcala",
        "Antoine Lavoisier",
        "Antonie van Leeuwenhoek",
        "Antonio Meucci",
        "Antony Hewish",
        "Archimedes",
        "Aristarchus",
        "Aristotle",
        "Arnold Orville Beckman",
        "Arnold Sommerfeld",
        "Arthur Eddington",
        "Artturi Virtanen",
        "Avicenna",
        "B. F. Skinner",
        "Barbara McClintock",
        "Beatrix Potter",
        "Benjamin Cabrera",
        "Benjamin Franklin",
        "Benjamin Thompson",
        "Bernardo Houssay",
        "Bill Nye",
        "Blaise Pascal",
        "Brahmagupta",
        "Brian Cox",
        "C. V. Raman",
        "Carl Bosch",
        "Carl Friedrich Gauss",
        "Carl Sagan",
        "Carolus Linnaeus",
        "Charles Babbage",
        "Charles Darwin",
        "Charles Lyell",
        "Charles Sherrington",
        "Charles-Augustin de Coulomb",
        "Chen-Ning Yang",
        "Christiaan Huygens",
        "Christiane Nusslein-Volhard",
        "Clarence Birdseye",
        "Claude Bernard",
        "Claude Levi-Strauss",
        "Clyde Tombaugh",
        "Daniel Bernoulli",
        "David Bohm",
        "David Hilbert",
        "Dian Fossey",
        "Dmitri Mendeleev",
        "Dorothy Hodgkin",
        "E. O. Wilson",
        "Edmund Halley",
        "Edward Jenner",
        "Edward Teller",
        "Edwin Herbert Land",
        "Edwin Hubble",
        "Elizabeth Blackwell",
        "Emil Adolf Behring",
        "Emil Fischer",
        "Emil Kraepelin",
        "Emile Berliner",
        "Enrico Fermi",
        "Eratosthenes",
        "Ernest Rutherford",
        "Ernesto Illy",
        "Ernst Haeckel",
        "Ernst Ising",
        "Ernst Mach",
        "Ernst Mayr",
        "Ernst Werner von Siemens",
        "Erwin Chargaff",
        "Erwin Schrödinger",
        "Euclid",
        "Evangelista Torricelli",
        "Francesco Redi",
        "Francis Bacon",
        "Francis Crick",
        "Francis Galton",
        "Frank Hornby",
        "Franz Boas",
        "Frederick Gowland Hopkins",
        "Frederick Sanger",
        "Frederick Soddy",
        "Friedrich August Kekulé",
        "Friedrich Wöhler",
        "Fritz Haber",
        "Galen",
        "Galileo Galilei",
        "Gene Shoemaker",
        "Georg Ohm",
        "George Beadle",
        "George Gamow",
        "George Gaylord Simpson",
        "George Washington Carver",
        "Georges-Louis Leclerc, Comte de Buffon",
        "Gertrude Elion",
        "Gerty Theresa Cori",
        "Glenn Seaborg",
        "Gottfried Leibniz",
        "Gottlieb Daimler",
        "Grace Murray Hopper",
        "Gregor Mendel",
        "Guglielmo Marconi",
        "Gustav Kirchoff",
        "Gustav Ludwig Hertz",
        "Hans Bethe",
        "Hans Christian Oersted",
        "Hans Selye",
        "Harriet Quimby",
        "Hedy Lamarr",
        "Heike Kamerlingh Onnes",
        "Heinrich Hertz",
        "Hendrik Antoon Lorentz",
        "Henri Becquerel",
        "Henrietta Swan Leavitt",
        "Henry Bessemer",
        "Henry Cavendish",
        "Henry David Thoreau",
        "Henry Ford",
        "Henry Moseley",
        "Hermann Rorschach",
        "Hermann von Helmholtz",
        "Homi Jehangir Bhabha",
        "Humphry Davy",
        "Ibn Battuta",
        "Ibn Rushd",
        "Inge Lehmann",
        "Irene Joliot-Curie",
        "Isaac Newton",
        "Ivan Pavlov",
        "J. Hans D. Jensen",
        "J. J. Thomson",
        "J. Robert Oppenheimer",
        "Jagadish Chandra Bose",
        "James Chadwick",
        "James Clerk Maxwell",
        "James Dwight Dana",
        "James Hutton",
        "James Prescott Joule",
        "James Watson",
        "James Watt",
        "Jan Baptist von Helmont",
        "Jane Goodall",
        "Jane Marcet",
        "Jean Andre Deluc",
        "Jean Piaget",
        "Jean-Baptiste Lamarck",
        "Jim Al-Khalili",
        "Jocelyn Bell Burnell",
        "Johannes Kepler",
        "John Archibald Wheeler",
        "John Bardeen",
        "John Dalton",
        "John Locke",
        "John Logie Baird",
        "John Napier",
        "John Needham",
        "John Ray",
        "John von Neumann",
        "Jonas Salk",
        "Joseph Banks",
        "Joseph Lister",
        "Joseph Priestley",
        "Justus von Liebig",
        "K. Eric Drexler",
        "Karl F. Herzfeld",
        "Karl Landsteiner",
        "Katharine Burr Blodgett",
        "Keisuke Ito",
        "Kip S. Thorne",
        "Konrad Lorenz",
        "Kristian Birkeland",
        "Lee De Forest",
        "Leland Clark",
        "Leo Szilard",
        "Leon Foucault",
        "Leonardo da Vinci",
        "Leonhard Euler",
        "Lester R. Brown",
        "Linus Pauling",
        "Lise Meitner",
        "Louis Agassiz",
        "Louis de Broglie",
        "Louis Pasteur",
        "Lucretius",
        "Ludwig Boltzmann",
        "Luigi Galvani",
        "Luis Alvarez",
        "Luther Burbank",
        "Lynn Margulis",
        "Mae Carol Jemison",
        "Marcello Malpighi",
        "Marguerite Perey",
        "Maria Gaetana Agnesi",
        "Maria Goeppert-Mayer",
        "Maria Mitchell",
        "Marie Curie",
        "Mario Molina",
        "Mary Anning",
        "Max Born",
        "Max Delbruck",
        "Max Planck",
        "Max von Laue",
        "Michael E. Brown",
        "Michael Faraday",
        "Michio Kaku",
        "Mihailo Petrovic Alas",
        "Mohammad Abdus Salam",
        "Muhammad ibn Musa al-Khwarizmi",
        "Murray Gell-Mann",
        "Neil deGrasse Tyson",
        "Niccolo Leoniceno",
        "Nicholas Culpeper",
        "Nicolaus Copernicus",
        "Niels Bohr",
        "Nikola Tesla",
        "Noam Chomsky",
        "Omar Khayyam",
        "Otto Hahn",
        "Otto Haxel",
        "Paul Dirac",
        "Paul Ehrlich",
        "Pearl Kendrick",
        "Percy Lavon Julian",
        "Peter Debye",
        "Pierre Curie",
        "Pierre de Fermat",
        "Pierre-Simon Laplace",
        "Prafulla Chandra Ray",
        "Prokop Divis",
        "Pythagoras",
        "Rachel Carson",
        "Ramon Barba",
        "Randy Pausch",
        "René Descartes",
        "Richard Feynman",
        "Rita Levi-Montalcini",
        "Robert Bosch",
        "Robert Boyle",
        "Robert Brown",
        "Robert Bunsen",
        "Robert Goddard",
        "Robert Hooke",
        "Robert Koch",
        "Ronald Ross",
        "Rosalind Franklin",
        "Rudolf Christian Karl Diesel",
        "Rudolf Virchow",
        "Salim Ali",
        "Sally Ride",
        "Santiago Ramon y Cajal",
        "Sergei Winogradsky",
        "Sheldon Lee Glashow",
        "Shintaro Hirase",
        "Sigmund Freud",
        "Srinivasa Ramanujan",
        "Stephanie Kwolek",
        "Stephen Hawking",
        "Steven Chu",
        "Subrahmanyan Chandrasekhar",
        "Svante Arrhenius",
        "Sven Wingqvist",
        "Thabit ibn Qurra",
        "Thales of Miletus",
        "Theodor Schwann",
        "Theodosius Dobzhansky",
        "Thomas Alva Edison",
        "Thomas Burnet",
        "Thomas Hunt Morgan",
        "Thomas Kuhn",
        "Thomas Midgeley Jr.",
        "Thomas Newcomen",
        "Thomas Willis",
        "Tim Noakes",
        "Timothy John Berners-Lee",
        "Trofim Lysenko",
        "Tycho Brahe",
        "Ukichiro Nakaya",
        "Virginia Apgar",
        "Vladimir Vernadsky",
        "Walter Schottky",
        "Walther Wilhelm Georg Bothe",
        "Werner Heisenberg",
        "Wernher Von Braun",
        "Wilbur and Orville Wright",
        "Wilhelm Ostwald",
        "Wilhelm Röntgen",
        "Wilhelm Wundt",
        "Willard Frank Libby",
        "Willard Gibbs",
        "William Bayliss",
        "William Buckland",
        "William Harvey",
        "William Herschel",
        "William Hopkins",
        "William John Swainson",
        "William Ramsay",
        "William Smith",
        "William Thomson",
        "Wolfgang Ernst Pauli",
        "Zora Neale Hurston"
];

const schools :List(Text) = [
  "Caltech",
  "Carnegie Mellon",
  "Harvey Mudd",
  "Northeastern",
  "Penn State",
  "University of Pittsburgh",
  "UCLA"
];

const emails :List(Text) = [
  "alice@example.com",
  "bob@example.com",
  "carol@example.com",
  "anonymous@example.com",
  "a@example.com",
  "b@example.com",
  "c@example.com",
  "d@example.com",
  "e@example.com",
];
